config/routes.rb
Rails.application.routes.draw do
  root 'clockins#index'
  resources :clockouts
  resources :clockins
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clockin.rb
class Clockin < ApplicationRecord
  belongs_to :user
end

app/models/clockout.rb
class Clockout < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clockins_controller.rb
class ClockinsController < ApplicationController
  before_action :set_clockin, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /clockins
  # GET /clockins.json
  def index
    @clockins = Clockin.all
  end

  # GET /clockins/1
  # GET /clockins/1.json
  def show
  end

  # GET /clockins/new
  def new
    @clockin = Clockin.new
  end

  # GET /clockins/1/edit
  def edit
  end

  # POST /clockins
  # POST /clockins.json
  def create
    @clockin = Clockin.new(clockin_params)
    respond_to do |format|
      if @clockin.save
        format.html { redirect_to @clockin, notice: 'Clockin was successfully created.' }
        format.json { render :show, status: :created, location: @clockin }
      else
        format.html { render :new }
        format.json { render json: @clockin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clockins/1
  # PATCH/PUT /clockins/1.json
  def update
    respond_to do |format|
      if @clockin.update(clockin_params)
        format.html { redirect_to @clockin, notice: 'Clockin was successfully updated.' }
        format.json { render :show, status: :ok, location: @clockin }
      else
        format.html { render :edit }
        format.json { render json: @clockin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clockins/1
  # DELETE /clockins/1.json
  def destroy
    @clockin.destroy
    respond_to do |format|
      format.html { redirect_to clockins_url, notice: 'Clockin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clockin
      @clockin = Clockin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clockin_params
      params.require(:clockin).permit(:location, :user_id)
    end
end

app/controllers/clockouts_controller.rb
class ClockoutsController < ApplicationController
  before_action :set_clockout, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /clockouts
  # GET /clockouts.json
  def index
    @clockouts = Clockout.all
  end

  # GET /clockouts/1
  # GET /clockouts/1.json
  def show
  end

  # GET /clockouts/new
  def new
    @clockout = Clockout.new
  end

  # GET /clockouts/1/edit
  def edit
  end

  # POST /clockouts
  # POST /clockouts.json
  def create
    @clockout = Clockout.new(clockout_params)

    respond_to do |format|
      if @clockout.save
        format.html { redirect_to @clockout, notice: 'Clockout was successfully created.' }
        format.json { render :show, status: :created, location: @clockout }
      else
        format.html { render :new }
        format.json { render json: @clockout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clockouts/1
  # PATCH/PUT /clockouts/1.json
  def update
    respond_to do |format|
      if @clockout.update(clockout_params)
        format.html { redirect_to @clockout, notice: 'Clockout was successfully updated.' }
        format.json { render :show, status: :ok, location: @clockout }
      else
        format.html { render :edit }
        format.json { render json: @clockout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clockouts/1
  # DELETE /clockouts/1.json
  def destroy
    @clockout.destroy
    respond_to do |format|
      format.html { redirect_to clockouts_url, notice: 'Clockout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clockout
      @clockout = Clockout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def clockout_params
      params.require(:clockout).permit(:location, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clockins_helper.rb
module ClockinsHelper
end

app/helpers/clockouts_helper.rb
module ClockoutsHelper
end

app/views/clockins/_form.html.erb
<%= form_with(model: clockin, local: true) do |form| %>
  <% if clockin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clockin.errors.count, "error") %> prohibited this clockin from being saved:</h2>

      <ul>
        <% clockin.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clockins/edit.html.erb
<h1>Editing Clockin</h1>

<%= render 'form', clockin: @clockin %>

<%= link_to 'Show', @clockin %> |
<%= link_to 'Back', clockins_path %>

app/views/clockins/index.html.erb
<%= javascript_pack_tag 'hello_react' %>
<%= stylesheet_pack_tag 'hello_react' %>

app/views/clockins/new.html.erb
<h1>New Clockin</h1>

<%= render 'form', clockin: @clockin %>

<%= link_to 'Back', clockins_path %>

app/views/clockins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @clockin.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @clockin.user_id %>
</p>

<%= link_to 'Edit', edit_clockin_path(@clockin) %> |
<%= link_to 'Back', clockins_path %>

app/views/clockouts/_form.html.erb
<%= form_with(model: clockout, local: true) do |form| %>
  <% if clockout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clockout.errors.count, "error") %> prohibited this clockout from being saved:</h2>

      <ul>
        <% clockout.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clockouts/edit.html.erb
<h1>Editing Clockout</h1>

<%= render 'form', clockout: @clockout %>

<%= link_to 'Show', @clockout %> |
<%= link_to 'Back', clockouts_path %>

app/views/clockouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clockouts</h1>

<table>
  <thead>
    <tr>
      <th>Location</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clockouts.each do |clockout| %>
      <tr>
        <td><%= clockout.location %></td>
        <td><%= clockout.user_id %></td>
        <td><%= link_to 'Show', clockout %></td>
        <td><%= link_to 'Edit', edit_clockout_path(clockout) %></td>
        <td><%= link_to 'Destroy', clockout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Clockout', new_clockout_path %>

app/views/clockouts/new.html.erb
<h1>New Clockout</h1>

<%= render 'form', clockout: @clockout %>

<%= link_to 'Back', clockouts_path %>

app/views/clockouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Location:</strong>
  <%= @clockout.location %>
</p>

<p>
  <strong>User:</strong>
  <%= @clockout.user_id %>
</p>

<%= link_to 'Edit', edit_clockout_path(@clockout) %> |
<%= link_to 'Back', clockouts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exercise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>